### ISSUE TITLE
Using  as invocation_layer_class will result in invalid yml 

### ISSUE THREAD

**Issue by CoLdIcE42** [LLukas22/vLLM-haystack-adapter#9]
Hi,
Im using a PromptModel with the following config:
```
model = PromptModel(
            model_name_or_path="", 
            invocation_layer_class=vLLMInvocationLayer, 
            max_length=1024, 
            api_key="EMPTY", 
            model_kwargs={
                "api_base" : "http://localhost:8000/v1" , 
            })
```

**the to yml method creates the following output for the PromptModel:**
```
- name: PromptModel
  params:
    api_key: EMPTY
    invocation_layer_class: !!python/name:vllm_haystack.vLLMInvocationLayer ''
    max_length: 1024
    model_kwargs:
      api_base: http://localhost:8100/v1
      maximum_context_length: 2048
```

**when starting the docker-compose with a pipeline using the code above this will result in the following error:**
`haystack_docker-haystack-api-1      | yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:vllm_haystack.vLLMInvocationLayer'`

I installed vllm-haystack via pip in the Dockerfile.base to ensure it is present in the container. Still getting this error
